config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'server_error' => 'static_pages#server_error'

  get 'signup' => 'users#new'
  get 'ranking' => 'users#ranking'
  get 'delete_profile_image' => 'users#delete_profile_image'
  get 'battles/ranking' => 'battles#ranking'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'questions' => 'questions#category'
  get 'questions/all' => 'questions#index'

  get 'questions/humans' => 'questions#humans'
  get 'questions/nature' => 'questions#nature'
  get 'questions/languages' => 'questions#languages'
  get 'questions/math' => 'questions#math'
  get 'questions/recommended' => 'questions#recommended'
  get 'questions/upload' => 'questions#new'
  post 'questions/upload_questions'
  post 'questions/upload_candidates_data'

  get 'medals' => 'medals#index'

  get '/generate_random_user', :to=>"battles#generate_random_user"

  get 'notifications' => 'notifications#index'

  get 'answer_exam' => 'exams#answer_exam'
  get 'select_exam' => 'exams#select_exam'
  get 'exam_result' => 'exams#exam_result'
  get 'exams_statistics' => 'exams#exams_statistics'
  delete 'cancel_exam' => 'exams#cancel_exam'

  resources :posts
  resources :comments

  post 'comments/create' => 'comments#create'

  resources :topics
  resources :posts do
    resources :comments
  end

  resources :users
  resources :questions do
    member do
      post 'answer'
      post 'next' => 'questions#next_question'
    end
  end

  resources :battles do
    member do
      post 'answer'
      get 'finish'
    end
  end

  resources :posts do
    member do
      get 'rate_post' => 'posts#rate_post'
    end
  end

  resources :comments do
    member do
      get 'rate_comment' => 'comments#rate_comment'
    end
  end

  resources :battles do
    member do
      get 'result' => 'battles#result'
    end
  end

  resources :notifications do
    get :read, on: :collection
  end

  get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/question.rb
class Question < ActiveRecord::Base

  before_save { self.area = area.mb_chars.downcase.to_s }
  before_save { self.right_answer = right_answer.downcase }

  validates :year, presence: true, length: { maximum: 4 }
  validates :area, presence: true
  validates :number, presence: true, length: { maximum: 3 }
  validates :enunciation, presence: true
  validates :alternatives, presence: true
  validates :right_answer, presence: true, length: { maximum: 1 }
  validates :number, uniqueness: { scope: [:year] }

  has_many :texts

  validate do
    check_alternatives_number
  end

  has_many :alternatives
  has_and_belongs_to_many :battles
  accepts_nested_attributes_for :alternatives, allow_destroy: true

  ALTERNATIVES_COUNT = 5

  def hit_rate
    hit_rate = self.tries == 0 ? 0 : (100 * (self.hits.to_f / self.tries)).round(2)
  end

  def next_question
    question = Question.where(area: self.area).where("id > ?", id).first
    question ? question : Question.where(area: self.area).first
  end

  def users_hit_rate
    users_hit_rate = self.users_tries == 0 ? 0 :
          (100 * (self.users_hits.to_f / self.users_tries)).round(2)
  end

  def total_hit_rate
    total_hit_rate = (100 * (self.hits + self.users_hits.to_f) / (self.tries + self.users_tries)).round(2)
    total_hit_rate = total_hit_rate.nan? ? 0.0 : total_hit_rate
  end

  def data
    [
      {"name" => "Enem","data" => {"Enem" => self.hit_rate}},
      {"name" => "Usuários","data" => {"Usuários" => self.users_hit_rate}},
      {"name" => "Todos","data" => {"Todos" => self.total_hit_rate}}
    ]
  end

  class << self
    def method_missing method_name, *args
      method_name = method_name.to_s
      if method_name.slice! /_questions/
        cmp_hash = { "beginner" => lambda { |hit_rate| hit_rate >= 75.0 },
                     "intermediate" => lambda { |hit_rate| hit_rate >= 30.0 && hit_rate < 75.0 },
                     "advanced" => lambda { |hit_rate| hit_rate < 30.0 } }
        questions = Question.where area: args.first
        questions.select { |q| cmp_hash[method_name].call q.total_hit_rate }
      else
        super
      end
    end
  end

  private

    def alternatives_count_valid?
      self.alternatives.size == ALTERNATIVES_COUNT
    end

    def check_alternatives_number
      unless alternatives_count_valid?
        errors.add(:alternatives, "cannot be less than 5")
      end
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user
  before_action :authenticate_admin, only: [ :new, :create, :edit, :destroy, :update ]

  include QuestionsHelper

  def index
    @questions = Question.all.order(:year, :number)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      flash[:success] = "Questão atualizada com sucesso!"
      redirect_to question_path
    else
      render 'edit'
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:success] = "Questão deletada com sucesso!"
    redirect_to questions_path
  end

  def answer
    question = Question.find(params[:id])
    @answer_letter = params[:alternative]

    if params[:alternative].blank?
      redirect_to_back(root_path)
    else
      current_user.update_attribute(:tried_questions, current_user.tried_questions << question.id)
      question.update_attribute(:users_tries, question.users_tries + 1)

      @correct_answer = (@answer_letter == question.right_answer)

      respond_to do |format|
        format.html { redirect_to questions_path }
        format.js { @correct_answer }
      end

      if @correct_answer
        question.update_attribute(:users_hits, question.users_hits + 1)
        unless current_user.accepted_questions.include? question.id
          current_user.accepted_questions.push(question.id)
          current_user.update_attribute(:points, current_user.points + 4)
        end
      end
    end
  end

  def category
  end

  def nature
    @questions = Question.where(area: "ciências da natureza e suas tecnologias").order(:year, :number)
  end

  def humans
    @questions = Question.where(area: "ciências humanas e suas tecnologias").order(:year, :number)
  end

  def languages
    @questions = Question.where(area: "linguagens, códigos e suas tecnologias").order(:year, :number)
  end

  def math
    @questions = Question.where(area: "matemática e suas tecnologias").order(:year, :number)
  end

  def recommended
    areas = ["ciências da natureza e suas tecnologias",
             "ciências humanas e suas tecnologias",
             "linguagens, códigos e suas tecnologias",
             "matemática e suas tecnologias"]
    @questions = []
    areas.each do |area|
      classification = current_user.classification(area)
      @questions = @questions | instance_eval("Question.#{classification}_questions('#{area}')")
    end
    @questions = @questions.select { |q| !current_user.accepted_questions.include? q.id }
  end

  def upload_questions
    uploaded_file = params[:questions_file]

    raise Exception if uploaded_file.nil?

    file_content = uploaded_file.read

    Parser.read_questions(file_content)

    flash[:success] = "Questões armazenadas com sucesso."
    redirect_to questions_path
  end

  def upload_candidates_data
    uploaded_file = params[:candidates_data_file]

    raise Exception if uploaded_file.nil?

    file_content = uploaded_file.read

    Parser.read_candidates_data(file_content, params[:test_year])

    flash[:success] = "Dados armazenados com sucesso."
    redirect_to questions_path
  end

  def next_question
    redirect_to Question.find(params[:id]).next_question
  end

  private

  def question_params
    params.require(:question).permit(:year,:area,:number,:enunciation,:reference,:image,:right_answer,:alternatives_attributes => [:id, :letter, :description])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper

  class Parser
    class << self

      def read_questions json_questions
        questions = JSON.parse(json_questions)["questions"]
        questions.each do |question|
          q = Question.new
          question.each do |attr, value|
            if attr == "text"
              value.each do |t|
                q.texts << Text.new(title: t["title"], paragraphs: t["paragraphs"],
                                    reference: t["reference"])
              end
            elsif attr == "alternatives"
              5.times do |i|
                q.alternatives.build
                q.alternatives[i].letter = value.keys[i]
                q.alternatives[i].description = value[value.keys[i]]
              end
            else
              eval "q.#{attr} = value"
            end
          end
          q.save
          t = Topic.create(name: "Questão #{q.number} - Ano #{q.year}", question_id: q.id, description: "Dúvidas e respostas sobre a questão #{q.number} da prova do ano #{q.year}")
        end
      end

      def read_candidates_data candidates_data, test_year
        candidates_data.each_line do |line|
          next if line == "\n"
          student_responses = line[/(A|B|C|D|E|'*'){180}/, 0]
          enem_feedback = line[/(0|1){1}(A|B|C|D|E){185}/, 0]
          test_booklet_types = line[/[0-9]{13}(A|B|C|D|E){185}/, 0]
          test_booklet_types_array = test_booklet_types.scan /.{3}/
          language_choice = enem_feedback.slice!(0).to_i
          enem_feedback.slice!(95 - (5 * language_choice), 5)
          student_hits = 0
          180.times do |i|
            question = Question.where(number: i, year: test_year).take
            next if question.nil?
            if student_responses[i] == enem_feedback[i]
              student_hits += 1
              question.hits += 1
            end
            question.tries += 1
            question.save
          end
          Candidate.create general_average: (100 * student_hits.to_f / 180).round(2)
        end
      end
    end
  end

end

app/views/questions/_category.html.erb
<% if !@questions.blank? %>
  <table class='table'>
    <thead>
      <th>Ano</th>
      <th>Número</th>
      <th>Enunciado</th>
    </thead>

    <% @questions.each do |t| %>
      <tr>
        <td><%= t.year %></td>
        <td><%= link_to t.number, "/questions/#{t.id}" %></td>
        <td><%= t.enunciation %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h3> Não existem recomendações de questões no momento. </h3>
<% end %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>

	<div>
		<%= f.label :year %>
		<%= f.text_field :year %>
	</div>
	<div>
		<%= f.label :area %>
		<%= f.text_field :area %>
	</div>
	<div>
		<%= f.label :number %>
		<%= f.text_field :number %>
	</div>
	<div>
		<%= f.label :enunciation %>
		<%= f.text_field :enunciation %>
	</div>
	<div>
		<%= f.label :reference %>
		<%= f.text_field :reference %>
	</div>
	<div>
		<%= f.label :image %>
		<%= f.text_field :image %>
	</div>

	<%= f.fields_for :alternatives do |ff| %>
		<div>
			<%= ff.label :letter %>
			<%= ff.text_field :letter %>

			<%= ff.label :description %>
			<%= ff.text_field :description %>
		</div>
	<% end %>
	<div>
		<%= f.label :right_answer %>
		<%= f.text_field :right_answer %>
	</div>

	<%= f.submit %>
<% end %>

app/views/questions/answer.js.erb
$('input.btn').hide();
$('input[type="radio"]').hide();
$('#jump-btn').html('Próxima questão');
$('#jump-btn').after("<%= j link_to 'Fórum', topic_path, class: 'btn btn-primary btn-sm button' %>");
$(".<%= j @answer_letter %>-description").after("<div class='alert alert-info'><%= j image_tag(@correct_answer ? 'correct-answer' : 'wrong-answer', alt: "", class: 'answer-feedback') %><%= @correct_answer ? 'Parabéns! Você ganhou 4 pontos!' : 'Você errou, tente novamente' %></div>");

app/views/questions/category.html.erb
<h1 class="content-title"> Categorias </h1>

<table class="category-images">
	<tr>
		<td><%= link_to image_tag("humanas.png"), questions_humans_path %></td>
		<td><%= link_to image_tag("natureza.png"), questions_nature_path %></td>
		<td><%= link_to image_tag("linguagens.png"), questions_languages_path %></td>
	</tr>
	<tr>
		<td><%= link_to image_tag("matematica.png"), questions_math_path %></td>
		<td><%= link_to image_tag("todas.png"), questions_all_path %></td>
        <td><%= link_to image_tag("sugeridas.png"), questions_recommended_path %></td>
	</tr>
</table>

app/views/questions/edit.html.erb
<h1>Edit question <%= @question.id %> (number <%= @question.number%>)</h1>

<% unless @question.errors.empty? %>
  <% flash.now[:danger] = @question.errors.full_messages.join("<br/>").html_safe %>
<% end %>

<%= render :partial => 'form' %>

app/views/questions/humans.html.erb
<h1>Ciências Humanas e suas Tecnologias</h1>
<%= render :partial => 'category' %>

app/views/questions/index.html.erb
<h1> Lista de Questões </h1>

<% if current_user.role_admin? %>
	<%= link_to 'Novas Questões', new_question_path, class: "btn btn-success"  %>
<% end %>

<% if !@questions.blank? %>
	<table class='table'>
		<thead>
			<th>Ano</th>
			<th>Número</th>
			<th>Área</th>
			<th>Enunciado</th>
		</thead>

		<% @questions.each do |t| %>
			<tr>
				<td class="align-center"><%= t.year %></td>
				<td class="align-center"><%= link_to t.number, "/questions/#{t.id}" %></td>
				<td><%= t.area %></td>
				<td><%= truncate(t.enunciation, length: 180, separator: ' ') %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<h3> Não há questões cadastradas no momento. </h3>
<% end %>

app/views/questions/languages.html.erb
<h1>Linguagens e Códigos e suas Tecnologias</h1>
<%= render :partial => 'category' %>

app/views/questions/math.html.erb
<h1>Matemática e suas Tecnologias</h1>
<%= render :partial => 'category' %>

app/views/questions/nature.html.erb
<h1>Ciências da Natureza e suas Tecnologias</h1>
<%= render :partial => 'category' %>

app/views/questions/new.html.erb
<h1 class="border-title">Upload de Dados</h1>

<div class="content-container">
  <div class="upload-forms-container">
    <%= form_tag({ action: :upload_questions }, multipart: true, class: 'upload-form',
                   id: 'questions-form') do %>
      <h2 class="form-title">Questões em JSON</h2>
      <span class="btn btn-default btn-file">
        Browse<%= file_field_tag 'questions_file' %>
      </span>
      <%= submit_tag 'Enviar', class: 'btn btn-primary btn-sm' %>
    <% end %>

    <%= form_tag({ action: :upload_candidates_data }, multipart: true, class: 'upload-form', id: 'candidates-data-form') do %>
      <h2 class="form-title">Dados dos candidatos do Enem</h2>
      <%= select_tag :test_year, options_for_select((2009..2012).to_a.collect { |x| x.to_s }), class: 'form-control' %>
      <span class="btn btn-default btn-file">
        Browse<%= file_field_tag 'candidates_data_file' %>
      </span>
      <%= submit_tag 'Enviar', class: 'btn btn-primary btn-sm' %>
    <% end %>
  </div>
</div>

app/views/questions/recommended.html.erb
<h1>Questões Recomendadas</h1>
<%= render :partial => 'category' %>

app/views/questions/show.html.erb
<p></p>
<div class="buttons-questions">
  <% if current_user.role_admin? %>
    <%= link_to "Editar", edit_question_path, class: "btn btn-primary", id: "btn-edit" %>
    <%= link_to "Deletar", question_path, :method => :delete, class: "btn btn-danger", id: "btn-delete", data: { confirm: "Você tem certeza que deseja excluir esta questão?" } %>
  <% end %>
</div>

<div class="question">
  <h1>Questão <%= @question.number%></h1>
  <h2>Ano: <%= @question.year %></h2>

  <div class='question-index'>
    <p><%= @question.area %></p>
  </div>

  <% @question.texts.each do |t| %>
    <h4 class="question-title"><%= t.title %></h4>
    <% t.paragraphs.each do |p| %>
      <p class="question-text"><%= p %></p>
    <% end %>
    <p class="question-text-reference"><%= t.reference %></p>
  <% end %>

  <% unless @question.image.empty? %>
    <%= image_tag(@question.image , class: 'img-responsive question-img') %>
  <% end %>

  <p class="question"><%= @question.enunciation %></p>


  <%= form_tag answer_question_path, remote: true do %>
    <% @question.alternatives.each do |f| %>
      <div class="alternative">
        <%= radio_button_tag(:alternative, f.letter) %>
        <%= label_tag(f.letter.to_s, f.letter.to_s + ")") %>
        <span class="<%= f.letter.to_s %>-description"><%= f.description %></span>
      </div>
    <% end %>

  <%= submit_tag "Responder", class: 'answer btn btn-primary btn-sm button', id: 'answer-btn' %>
  <%= link_to "Pular", next_question_path, method: :post, class: 'btn btn-primary btn-sm button', id: 'jump-btn' %>

  <% end %>

<p>
  <%= yield :charts_js %>
  <%= bar_chart @question.data, colors: ["#009900", "#BBBB00" , "#0080FF"],
  min: 0,
  max: 100,
  library: {backgroundColor: "#eee",
            isStacked: true,
            title: 'Desempenho da Questão  (Porcentagem de acertos por tentativa)',

  } %>
</p>

</div>