config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'server_error' => 'static_pages#server_error'

  get 'signup' => 'users#new'
  get 'ranking' => 'users#ranking'
  get 'delete_profile_image' => 'users#delete_profile_image'
  get 'battles/ranking' => 'battles#ranking'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'questions' => 'questions#category'
  get 'questions/all' => 'questions#index'

  get 'questions/humans' => 'questions#humans'
  get 'questions/nature' => 'questions#nature'
  get 'questions/languages' => 'questions#languages'
  get 'questions/math' => 'questions#math'
  get 'questions/recommended' => 'questions#recommended'
  get 'questions/upload' => 'questions#new'
  post 'questions/upload_questions'
  post 'questions/upload_candidates_data'

  get 'medals' => 'medals#index'

  get '/generate_random_user', :to=>"battles#generate_random_user"

  get 'notifications' => 'notifications#index'

  get 'answer_exam' => 'exams#answer_exam'
  get 'select_exam' => 'exams#select_exam'
  get 'exam_result' => 'exams#exam_result'
  get 'exams_statistics' => 'exams#exams_statistics'
  delete 'cancel_exam' => 'exams#cancel_exam'

  resources :posts
  resources :comments

  post 'comments/create' => 'comments#create'

  resources :topics
  resources :posts do
    resources :comments
  end

  resources :users
  resources :questions do
    member do
      post 'answer'
      post 'next' => 'questions#next_question'
    end
  end

  resources :battles do
    member do
      post 'answer'
      get 'finish'
    end
  end

  resources :posts do
    member do
      get 'rate_post' => 'posts#rate_post'
    end
  end

  resources :comments do
    member do
      get 'rate_comment' => 'comments#rate_comment'
    end
  end

  resources :battles do
    member do
      get 'result' => 'battles#result'
    end
  end

  resources :notifications do
    get :read, on: :collection
  end

  get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :active_battles, class_name: 'Battle', foreign_key: 'player_1_id'
  has_many :passive_battles, class_name: 'Battle', foreign_key: 'player_2_id'
  has_many :won_battles, class_name: 'Battle', foreign_key: 'winner'

  has_many :notifications
  has_and_belongs_to_many :medals

  serialize :accepted_questions, Array
  serialize :tried_questions, Array
  serialize :answered_exams, Array
  serialize :exam_performance, Array

  before_save { self.email = email.downcase }

  has_secure_password

  has_attached_file :profile_image
  validates_attachment :profile_image,
      content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length:{maximum: 60}
  validates :nickname, presence: true, length:{maximum: 40}, uniqueness: true
  validates :email, presence: true, length:{maximum: 255},
  format: { with:  VALID_EMAIL },
  uniqueness: { case_sensitive: false }
  validates :password, length:{minimum: 8}, presence: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Password.create(string, cost: cost)
  end

  def count_questions_by_area(area)
    i = 0
    self.accepted_questions.each do |t|
      if Question.find(t).area == area
        i = i+1
      end
    end
    i
  end

  def find_position_in_ranking
    ranking = User.all.order(:points).reverse
    for i in 0...ranking.count
      return i+1 if ranking[i].id == self.id
    end
  end

  def total_accepted_questions
    self.accepted_questions.count
  end

  def data
    [
      ["Matemática", self.count_questions_by_area('matemática e suas tecnologias')],
      ["Natureza", self.count_questions_by_area('ciências da natureza e suas tecnologias')],
      ["Linguagens", self.count_questions_by_area('linguagens, códigos e suas tecnologias')],
      ["Humanas", self.count_questions_by_area('ciências humanas e suas tecnologias')]
    ]
  end

  def sum_exam_performance
    self.exam_performance.empty? ? 0 : self.exam_performance.inject(:+)
  end

  def progress
      (100 * self.total_accepted_questions.to_f/Question.all.count).round(2)
  end

  def battles
    (self.active_battles + self.passive_battles).sort
  end

  def average_performance area
    accepted_questions = []
    tried_questions = []
    self.accepted_questions.each do |question_id|
      q = Question.find question_id
      accepted_questions << q if q.area == area
    end
    self.tried_questions.each do |question_id|
      q = Question.find question_id
      tried_questions << q if q.area == area
    end
    result = accepted_questions.count.to_f / tried_questions.count
    result.nan? ? 0.0 : result
  end

  def classification area
    performance = self.average_performance area
    performance *= 100
    if performance >= 0 && performance <= 30
      "beginner"
    elsif performance > 30 && performance <= 60
      "intermediate"
    else
      "advanced"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user, except: [:ranking, :new, :create]
  before_action :verify_user_permission, only: [:edit, :destroy]

  def new
    @home_page = true
    @user = User.new
    redirect_to current_user if logged_in?
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Usuário foi deletado"
    redirect_to users_path
  end

  def show
    @user = User.find(params[:id])
    find_level current_user.points
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Usuário criado com sucesso!"
      log_in @user
      first_notification
      redirect_to root_path
    else
      @home_page = true
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success]= "Usuário atualizado"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

  def ranking
    @home_page = true unless logged_in?
    @users = User.order(:points).reverse
  end

  def delete_profile_image
    unless current_user.profile_image_file_name.empty?
      current_user.update_attribute(:profile_image_file_name,"")
      flash[:success] = "Foto de perfil removida com sucesso!"
    else
      flash[:danger] = "Não há foto de perfil para ser removida."
    end
    redirect_to user_path(current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :level, :points, :nickname, :password_digest,:password, :password_confirmation, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def top10
    ranking = User.all.order(:points).reverse
    @top10 = ranking.take(10)
  end

  #returns level of user without updating it
  def find_level user_points
    @user_level = (Math.sqrt 2*user_points).to_i
  end

  #update user level
  def update_user_level
    current_user.update_attribute(:level,@user_level)
    @user_level = current_user.level
  end
  
end

app/views/users/_form_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      O registro contém <%= pluralize(@user.errors.count, "erro", "erros") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_medals.html.erb
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#medal_modal">Medalhas</button>

<div id="medal_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">
          <% if @user.id == current_user.id %>
            Minhas medalhas
          <% else %>
           Medalhas de <%= @user.name %>
          <% end %>
         </h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <% unless @user.medals.empty? %>
            <% @user.medals.each do |medal| %>
              <div class="col-sm-6 col-md-3">
                <div class="thumbnail" id="user_medals">
                  <%= image_tag medal.image %>
                  <p class="medal_name">
                    <b><%= medal.name %></b>
                  </p>
                  <p class="medal_description">
                    <%= medal.description %>
                  </p>
                </div>
              </div>
            <% end %>
          <% else %>
            <% if @user.id == current_user.id %> Você
            <% else %> <%= @user.name %>
            <% end %>
            não tem nenhuma medalha
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>

  </div>
</div>

app/views/users/_new_level.html.erb
<div id="new_level_modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Parabéns!!! Você alcançou o nível <%= @user_level %></h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<script>
  $('#new_level_modal').modal('show');
</script>

app/views/users/_profile_sidebar.html.erb
<div class="col-sm-3">
  <div class="profile-sidebar">
    <div class="profile-image">
      <%= link_to image_tag(
        current_user.profile_image_file_name.blank? ? "profiles_images/default" : current_user.profile_image.url, alt: "Profile image"), "/users/#{current_user.id}" %>
    </div>
    <div class="profile-information">
      <p id="user-name"><%= current_user.name %></p>
      <p id="user-level"><strong>Nível:</strong> <%= current_user.level %></p>
      <p id="user-rank"><strong>Posição:</strong> <%= current_user.find_position_in_ranking %>º</p>
      <p><strong>Resolvido:</strong> <%= pluralize(current_user.total_accepted_questions, 'questão' ,'questões')%></p>
      <%= link_to "Meu Desempenho", exams_statistics_path, class: 'btn btn-primary', id:'statistics' %>
      <a href="/medals" class="btn btn-success"><%= image_tag("star.png") %><span>Medalhas</span></a>
    </div>
    <%= render 'users/ranking' %>
  </div>
</div>

app/views/users/_ranking.html.erb
<table class="ranking">
  <thead>
    <tr class="clickable-row" data-href=<%= ranking_path %> >
      <th><%= link_to image_tag("trophy.jpg"), ranking_path %> <span>TOP 10</span></th>
    </tr>
  </thead>
  <tbody>
  <% top10.each do |x| %>
    <tr>
      <td><%= link_to x.name, "/users/#{x.id}" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/battle_ranking.html.erb
<h1>Ranking da Batalha</h1>

<table class="table">
  <thead>
    <th>Posição</th>
    <th>Nome</th>
    <th>Pontos da Batalha</th>
    <th>Batalhas vencidas</th>
  </thead>
  <tbody>
    <% i = 0 %>
    <% @users.each do |user| %>
    <tr>
        <td><%= i = i+1 %>º</td>
        <td><%= link_to user.name, "/users/#{user.id}" %></td>
        <td><%= user.battle_points %></td>
        <td><%= user.wins %></td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/users/edit.html.erb
<h1> Alterar Dados </h1>

<%= render 'form_errors' %>

<%= form_for(@user) do |f| %>
  <%= f.label :nickname, "Nome de Usuário" %>
  <%= f.text_field :nickname, class: 'form-control' %>
  <%= f.label :name, "Nome Completo" %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label :email, "E-mail" %>
  <%= f.text_field :email, class: 'form-control' %>
  <%= f.label :password, "Senha" %>
  <%= f.password_field :password, class: 'form-control' %>
  <%= f.label :password_confirmation, "Confirmar senha" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <div>
    <%= f.label :profile_image, "Foto de Perfil" %>
    <% unless current_user.profile_image_file_name.blank? %>
    <%= link_to 'Remover foto', delete_profile_image_path, class: 'btn btn-danger', id: 'delete-image', data: { confirm: "Você tem certeza que deseja remover a foto?" } %>
  <% end %>
  </div>
  <span class="btn btn-default btn-file">
    Browse<%= f.file_field :profile_image, class: 'form-control' %>
  </span>
  <%= f.submit "Atualizar Dados", class: 'btn btn-primary' %>

<% end %>

app/views/users/index.html.erb
<h1> Usuários </h1>

<table class="table">
  <thead>
    <th>Nome</th>
    <th>Nível</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
        <td><%= link_to "#{user.name}", "/users/#{user.id}" %></td>
        <td><%= user.level %></td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<h1>Cadastro</h1>

<%= render 'form_errors' %>

<%= form_for(@user) do |f| %>
  <%= f.label :nickname, "Nome de Usuário" %>
  <%= f.text_field :nickname, class: 'form-control' %>
  <%= f.label :name, "Nome Completo" %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label :email, "E-mail" %>
  <%= f.text_field :email, class: 'form-control' %>
  <%= f.label :password, "Senha" %>
  <%= f.password_field :password, class: 'form-control' %>
  <%= f.label :password_confirmation, "Confirmar senha" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <div>
    <%= f.label :profile_image, "Foto de Perfil" %>
  </div>
  <span class="btn btn-default btn-file">
    Browse<%= f.file_field :profile_image, class: 'form-control' %>
  </span>
  <%= f.submit "Cadastrar", class: 'btn btn-primary' %>

<% end %>

app/views/users/ranking.html.erb
<h1>Ranking Geral</h1>

<table class="table">
  <thead>
    <th>Posição</th>
    <th>Nome</th>
    <th>Pontos</th>
    <th>Nível</th>
  </thead>
  <tbody>
    <% i = 0 %>
    <% @users.each do |user| %>
    <tr>
        <td><%= i = i+1 %>º</td>
        <td><%= link_to user.name, "/users/#{user.id}" %></td>
        <td><%= user.points %></td>
        <td><%= user.level %></td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<% if @user_level != current_user.level %>
    <%= render partial: 'users/new_level.html.erb' %>
    <% update_user_level %>
<% end %>

<div class="buttons-questions">
  <% if current_user.role_admin? || current_user.id == @user.id %>
    <%= link_to "Editar", edit_user_path, class: "btn btn-primary" %>
    <%= link_to "Excluir", user_path, :method => :delete,  class: "btn btn-danger", data: { confirm: "Você tem certeza que deseja excluir seu usuário?" } %>
  <% end %>
</div>

<h1><%= @user.name %></h1>

<% unless @user.accepted_questions.blank? %>
  <%= pie_chart @user.data, colors: ["red", "#0080FF" , "#009900", "#EEEE00"] %>
<% else %>
  <h4 id="no-questions"><center>Você ainda não respondeu nenhuma questão</center></h4>
<% end %>

<table class="table">
  <tr>
    <td><b>Usuário:</b> <%= @user.nickname %></td>
  </tr>
  <tr>
    <td><b>Nível:</b> <%= @user.level %></td>
  </tr>
  <tr>
    <td><b>Membro desde:</b> <%= @user.created_at.strftime(" %d/%m/%Y ") %></td>
  </tr>
  <tr>
    <td><b>Pontos:</b> <%= @user.points %></td>
  </tr>
</table>


<div>
  <div class="row">
    <% @user.medals.reverse.take(4).each do |medal| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail" id="user_medals">
          <%= image_tag medal.image %>
          <p class="medal_name">
            <b><%= medal.name %></b>
          </p>
          <p class="medal_description">
            <%= medal.description %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: 'medals' %>

<div>
  <p>
    <b>Questões resolvidas: </b>
    <%= @user.total_accepted_questions %>
  </p>

  <% if @user.total_accepted_questions != 0 %>
    <table class = 'table'>
      <thead>
        <th>Número</th>
        <th>Área</th>
        <th>Ano</th>
      </thead>
      <% @user.accepted_questions.each do |a| %>
        <% accepted = Question.find(a) %>
        <tbody>
          <td><%= link_to "#{accepted.number}", "/questions/#{a}" %></td>
          <td><%= accepted.area %></td>
          <td><%= accepted.year %></td>
        </tbody>
      <% end %>
    </table>
  <% end %>
</div>