config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'server_error' => 'static_pages#server_error'

  get 'signup' => 'users#new'
  get 'ranking' => 'users#ranking'
  get 'delete_profile_image' => 'users#delete_profile_image'
  get 'battles/ranking' => 'battles#ranking'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'questions' => 'questions#category'
  get 'questions/all' => 'questions#index'

  get 'questions/humans' => 'questions#humans'
  get 'questions/nature' => 'questions#nature'
  get 'questions/languages' => 'questions#languages'
  get 'questions/math' => 'questions#math'
  get 'questions/recommended' => 'questions#recommended'
  get 'questions/upload' => 'questions#new'
  post 'questions/upload_questions'
  post 'questions/upload_candidates_data'

  get 'medals' => 'medals#index'

  get '/generate_random_user', :to=>"battles#generate_random_user"

  get 'notifications' => 'notifications#index'

  get 'answer_exam' => 'exams#answer_exam'
  get 'select_exam' => 'exams#select_exam'
  get 'exam_result' => 'exams#exam_result'
  get 'exams_statistics' => 'exams#exams_statistics'
  delete 'cancel_exam' => 'exams#cancel_exam'

  resources :posts
  resources :comments

  post 'comments/create' => 'comments#create'

  resources :topics
  resources :posts do
    resources :comments
  end

  resources :users
  resources :questions do
    member do
      post 'answer'
      post 'next' => 'questions#next_question'
    end
  end

  resources :battles do
    member do
      post 'answer'
      get 'finish'
    end
  end

  resources :posts do
    member do
      get 'rate_post' => 'posts#rate_post'
    end
  end

  resources :comments do
    member do
      get 'rate_comment' => 'comments#rate_comment'
    end
  end

  resources :battles do
    member do
      get 'result' => 'battles#result'
    end
  end

  resources :notifications do
    get :read, on: :collection
  end

  get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <nav>
      <ul id="name-footer">
        <li>Enem Amigo, 2015</li>
      </ul>
      <ul>
        <li><%= link_to "Ajuda", help_path %></li>
        <li><%= link_to "Sobre", about_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to image_tag("enem-amigo.png", alt: "Logo"),
              root_path %>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Início", root_path %></li>
        <% if current_user && current_user.role_admin? %>
          <li><%= link_to "Usuários", users_path %></li>
        <% end %>
        <% if logged_in? %>
          <li><%= link_to "Questões", questions_path %></li>
          <li><%= link_to "Batalha", battles_path %></li>
          <li><%= link_to "Prova", select_exam_path %></li>
          <li><%= link_to "Fórum", topics_path %></li>
          <li><%= link_to "Ranking", ranking_path %></li>

          <li class="dropdown">
            <a id="notification-dropdown" href="#" class="dropdown-toggle btn" data-toggle="dropdown">
            Notificações
            <% if current_user.notifications.where(visualized: false).count != 0 %>
              <span class="badge" id="notification-counter"><%= current_user.notifications.where(visualized: false).count %>
            <% end %> </span> <b class="caret"></b>
            </a>
            <ul id="notification-list" class="dropdown-menu">
              <% @current_user.notifications.reverse.take(10).each do |notification| %>
                <li><%= link_to truncate(notification.message, length: 50, separator: ' '), notification.link %></li>
              <% end %>
              <li class="divider"></li>
              <li>
              <%= link_to 'Ver mais', notifications_path %>
              </li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle btn" data-toggle="dropdown">
            Minha Conta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar meu perfil", edit_user_path(current_user) %></li>
              <% if current_user.role_admin? %>
                <li><%= link_to "Upload", questions_upload_path %></li>
              <% end %>
              <li class="divider"></li>
              <li>
              <%= link_to 'Sair', logout_path, method: 'delete' %>
              </li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "Cadastre-se", signup_path %></li>
        <% end %>
      </ul>

    </nav>
  </div>

</header>

<script>
    $(function() {
      $("#notification-dropdown").click(function(evt) {
        $.ajax("/notifications/read");
        $("#notification-counter").hide();
        evt.preventDefault();
      })
    })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield :title) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi" %>
  <%= javascript_include_tag "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @home_page ? 'homepage' : '' %>">

<%= render 'layouts/header' %>

<div class="container-fluid">

  <% flash.each do |message_type, message| %>
    <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
  <% end %>

  <div class="row">

    <% if logged_in? %>
      <%= render 'users/profile_sidebar' %>
      <div class="col-sm-9 content main-content">
        <%= yield %>
      </div>
    <% else %>
      <div class="col-sm-4 login-form content content-radius">
        <%= yield %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'layouts/footer' %>

</body>
</html>